### PR TITLE
Updated Invoice and Order to be Woocommerce 3 compatible

### PR DESCRIPTION
**Pull request by yratof**
Found millions of noticed in my error log this morning. Turns out, there are quite a few places that still use the pre-3 order methods.

Cleaned up these two pages causing me problems, there are plenty more I'll go through. But for now, these are what I've got

### CODE REVIEW

**Comment by slobodan** [comment]
@yratof Thank you. You mentioned you would go through other files, want me to keep this PR open for those commits as well? Either way works for us.

**Comment by yratof** [comment]
Just added one more commit. Should have everything in the /classes/ dir - should be ok to merge this now. if i find more, i'll collate them before making a new PR

**Comment by yratof** [comment]
Might be worth swapping out all the calls for klarna functions though, as listed in `/includes/klarna-wc-30-compatibility-functions.php` rather than just fixing. But there are no errors if you're not updating WC, so might be pointless? Either way, It'll stop all issues going forward if we created functions for all `$order->get_thing()`

**Comment by slobodan** [comment]
Those compatibility methods are going to be retired in a future version, now that WooCommerce 3.2.x is current (we support two previous major versions), so I'll just merge this one now.

I personally ran into merchants that don't update WooCommerce, while updating other plugins, that's why we had to add the compatibility functions file. Not sure why anyone would do this, but it happens.

Anyway, thanks for fixing this!

**Pull request merged**
