### PR TITLE
Disabled price rounding for klarna invoice. Fixes #141

### LINKED ISSUE #141: Prices should not be rounded for klarna invoice
When using klarna invoice the prices for order items are rounded. If you have prices with decimals, say "10.1" and order 10 of them you expect the total to be 101. With klarna invoice the total becomes 100.

Klarna plugin version - 2.5.4

```
// Klarna invoice uses this method to get the price
$klarna_item_price_including_tax = $order->get_item_total( $item, true );

// Looking at the definition of the function we can see that it rounds by default
public function get_item_total( $item, $inc_tax = false, $round = true ) { ... }

// The correct code in klarna should be:
$klarna_item_price_including_tax = $order->get_item_total( $item, true, false );
```

### PR DESCRIPTION
**Pull request by forsvunnet**
Fixes #141

### CODE REVIEW

**Comment by slobodan** [comment]
@forsvunnet Isn't it rounded to number of decimals that you have configured in your WooCommerce store? From `get_item_total` function

```$total = $round ? round( $total, wc_get_price_decimals() ) : $total;```

We should probably honor store settings and keep the total rounded then.

**Comment by forsvunnet** [comment]
@slobodan Yes, it's true that it rounds to what's specified in the woocommerce settings. The problem is that klarna only accepts per-item prices.

Let me use an example to demonstrate.

1. WooCommerce is set to use 0 decimals
2. A product has the price 10.2
3. In the front-end this is displayed as 10,-
4. A customer orders 20 x of the product
5. In WooCommerce the total at checkout is 204,-
6. Items are sent to klarna as 20 x 10,-
7. The klarna invoice is 200,-

Because klarna only accepts the item price it doesn't know that the order line total is if the price is rounded.

**Comment by slobodan** [comment]
@forsvunnet sadly, I'm very, very aware of this :) We went back and forth with Klarna on it also, and were not able to find a solution that would 100% work.

This is why we have it as a requirement to have at least two decimal places in your WC store:

https://docs.woocommerce.com/document/klarna/

Klarna needs the prices sent to it to be two decimal places * 100.

I'll think about this some more and get back to you tomorrow, but I do not think we should be changing anything here.

**Comment by forsvunnet** [comment]
You should not require the WooCommerce setting to be set to two decimals. The Woo setting is purely cosmetic and does not actually round prices, it only displays the rounded prices.
As per my example an item that costs 10.2 is displayed as 10,- but the price itself is never changed, so that if you add 3 to cart, the cart total itself is never rounded, only the display price in the cart total. eg, the total is still 30.6, but it's displayed as 31,-

The worst part of the current cart is probably the tax calculation which in woo might be set to 15% but because the plugin recalculates the tax based on the rounded prices the tax rate fluctuates a lot for low price items. 

Say an item costs 3.4 and the tax rate is 15% which makes the tax for the item 0.51.
The price is then rounded to 3, the tax rate is then calculated to be 0.51/3 = 17%

The store where we discovered this sells high quantity low cost goods so this bug causes huge problems when it comes to accounting. Eg an order with 1500 x products that costs 3.4 which should have cost 5100 is only billed 4500. Not to mention the customers confusion at the wildly varying tax rates.

To quote the article you've linked from the documentation:
>  You might think that this is something we as extension developers should solve so that the figures added to the WooCommerce order is the same as the ones sent to the payment provider.

Yes, yes I think this should be solved in the extension. Especially because it's very easy to fix.

What's the argument for not sending the correct numbers to klarna?

**Comment by slobodan** [comment]
Tax calculation is done differently:

https://github.com/krokedil/woocommerce-gateway-klarna/blob/master/classes/class-wc-to-klarna.php#L335

**Comment by slobodan** [comment]
Can you please make one change to your PR and I'll merge it.

For every change you made to use non-rounded prices, make sure the number sent to Klarna is an integer, they do not allow any decimal places. This could happen is the actual price is something like 10.008 and what needs to be sent to Klarna can't be 1000.8 but 1001 instead.

**Comment by forsvunnet** [comment]
@slobodan There's no need. Prices added through the `addArticle` method is run through a method called `fixValue`. 

```

    /**
     * Multiplies value with 100 and rounds it.
     * This fixes value/price/amount inputs so that KO can handle them.
     *
     * @param float $value value
     */
    private function fixValue(&$value)
    {
        $value = round($value * 100);
    }
```

**Comment by forsvunnet** [comment]
@slobodan The function you linked looks good for getting the tax rate, but it's unfortunately not used for klarna invoice https://github.com/krokedil/woocommerce-gateway-klarna/blob/master/classes/class-klarna-order.php#L135

**Comment by forsvunnet** [comment]
Don't merge yet. I found another bug. I'll fix and update the code, just give me a minute

**Comment by slobodan** [comment]
You're right, that was only Klarna Checkout, sorry about that.

Will wait, thanks.

**Comment by forsvunnet** [comment]
@slobodan It's ready now. I discovered that the `$order->get_line_tax` also does rounding before returning.

So a product costing 10.4 with 15% tax (1.56) would be calculated as 10.0 / 2.0 resulting in a 20% tax rate

**Comment by slobodan** [comment]
@forsvunnet it looks great, thank you for this PR.

I'll test it next week, and have it merged for next release.

**Comment by forsvunnet** [comment]
@slobodan Just following up on this. Ready to merge it?

**Comment by slobodan** [comment]
@forsvunnet sorry about huge delay on this, yes, merging it now. Thank you.

**Pull request merged**
